---
galaxy_info:
  role_name: demo_role
  author: automation-team
  description: Demo role for AAP 2.7
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
